In [6]:
import numpy as np
a= np.arange(15)
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
arr =np.array([1,2,3,4])
print (arr)

[1 2 3 4]


In [10]:
zero=np.zeros(5)
print(zero)

[0. 0. 0. 0. 0.]


In [12]:
one = np.ones(5)
print(one)

[1. 1. 1. 1. 1.]


In [14]:
zero_mat= np.zeros(6).reshape(2,3)
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
array1 =np.arange(10)
array2 =np.arange(5,10)
print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


In [19]:
mat1 = np.random.randint(10,50,(4,4))
print(mat1)

[[27 38 30 46]
 [39 35 48 33]
 [35 18 21 24]
 [41 39 36 21]]


In [26]:
mat2=np.random.randint(20,30,(2,2))
mat3=np.random.randint(10,20,(2,2))
print(mat2,"\n",mat3,"\n",mat2+mat3,"\n",mat2-mat3)

[[29 26]
 [24 27]] 
 [[17 16]
 [17 19]] 
 [[46 42]
 [41 46]] 
 [[12 10]
 [ 7  8]]


In [28]:
mat4=np.random.uniform(20,30,(2,2))
print(mat4)

[[26.49331114 23.3332836 ]
 [24.09339468 22.87928459]]


In [30]:
arr = np.arange(1,20)
even = arr[arr%2==0]
print(arr)
print(even)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10 12 14 16 18]


In [33]:
arr = np.arange(1,20)
odd= arr[arr%2==1]
print(odd)

[ 1  3  5  7  9 11 13 15 17 19]
